app_id: "2f35949a-8582-4dc5-b655-c45bc7721661"
app_secret: "wkxVlvE4ZH0oH_8xTAG-D31~wR49~H.a4e"
redirect: "https://lessonslearned.pythonanywhere.com/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/schemmer.onmicrosoft.com"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"