# Generated by Django 3.2 on 2023-03-09 19:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='client',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', on_delete=django.db.models.deletion.CASCADE, to='ll.client'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='marketsector',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', on_delete=django.db.models.deletion.CASCADE, to='ll.marketsector'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='memo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='projectnumber', chained_model_field='projectnumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='ll.memo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='projectlocation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', on_delete=django.db.models.deletion.CASCADE, to='ll.projectlocation'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='projectname',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', on_delete=django.db.models.deletion.CASCADE, to='ll.projectname'),
        ),
    ]
