# Generated by Django 3.2 on 2023-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0002_auto_20230309_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projectnumber',
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='projectnumber',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='projectnumber',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='projectlocation',
            name='projectnumber',
        ),
        migrations.RemoveField(
            model_name='projectname',
            name='projectnumber',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='marketsector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='memo',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='projectlocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='projectname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='projectnumber',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Marketsector',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
        migrations.DeleteModel(
            name='Projectlocation',
        ),
        migrations.DeleteModel(
            name='Projectname',
        ),
        migrations.DeleteModel(
            name='Projectnumber',
        ),
    ]
